baseurl = "http://bazhenov.me"
defaultcontentlanguage = "en"
languagecode = "ru"
theme = "hugo-coder"
title = "bazhenov.me"

paginate = 20

pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "dracula"

disqusShortname = "bazhenov"

[params]
author = "Denis Bazhenov"
description = "Denis Bazhenov's personal website"
gravatar = "dotsid@gmail.com"
info = "Software Developer"
keywords = "blog,developer,personal"

favicon_16 = "/img/favicon-16x16.png"
favicon_32 = "/img/favicon-32x32.png"

since = 2008

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

customSCSS = ["css/custom.scss"]

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

# Social links
[[params.social]]
icon = "fa fa-github fa-2x"
name = "Github"
url = "https://github.com/bazhenov"
weight = 1

[[params.social]]
icon = "fa fa-linkedin fa-2x"
name = "Linkedin"
url = "https://www.linkedin.com/in/denisbazhenov/"
weight = 3

[[params.social]]
icon = "fa fa-stack-overflow fa-2x"
name = "Linkedin"
url = "https://stackoverflow.com/users/53658/denis-bazhenov"
weight = 3

[[params.social]]
icon = "fa fa-twitter fa-2x"
name = "Twitter"
url = "https://twitter.com/denis_bazhenov"
weight = 4

# Menu links
[[menu.main]]
name = "Blog"
url = "blog/"
weight = 1

[[menu.main]]
name = "About"
url = "about/"
weight = 2

[outputFormats]
[outputFormats.RSS]
baseName = "rss"
mediatype = "application/rss"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
